env:
  - RELEASE_VERSION={{ if index .Env "SDPCTL_VERSION" }}{{ .Env.SDPCTL_VERSION }}{{ else }}dev{{ end }}
before:
  hooks:
    - make deps
builds:
  - id: sdpctl_linux
    main: ./main.go
    env:
      - CGO_ENABLED=0
    goos:
      - linux
    goarch:
      - amd64
      - arm64
    binary: "{{ if .IsSnapshot }}{{ .ProjectName }}_{{ .Os }}_{{ .Arch }}{{ else }}{{ .ProjectName }}{{ end }}"
    ldflags:
      - -s -w -X "github.com/appgate/sdpctl/cmd.version={{ .Env.RELEASE_VERSION }}"
      - -X "github.com/appgate/sdpctl/cmd.commit={{ .Commit }}"
      - -X "github.com/appgate/sdpctl/cmd.buildDate={{ .Date }}"
  - id: sdpctl_windows
    main: ./main.go
    env:
      - CGO_ENABLED=0
    goos:
      - windows
    goarch:
      - amd64
      - arm64
    binary: "{{ if .IsSnapshot }}{{ .ProjectName }}_{{ .Os }}_{{ .Arch }}{{ else }}{{ .ProjectName }}{{ end }}"
    ldflags:
      - -s -w -X "github.com/appgate/sdpctl/cmd.version={{ .Env.RELEASE_VERSION }}"
      - -X "github.com/appgate/sdpctl/cmd.commit={{ .Commit }}"
      - -X "github.com/appgate/sdpctl/cmd.buildDate={{ .Date }}"
  - id: sdpctl_darwin
    main: ./main.go
    env:
      - CGO_ENABLED=1
    goos:
      - darwin
    goarch:
      - amd64
      - arm64
    binary: "{{ if .IsSnapshot }}{{ .ProjectName }}_{{ .Os }}_{{ .Arch }}{{ else }}{{ .ProjectName }}{{ end }}"
    ldflags:
      - -s -w -X "github.com/appgate/sdpctl/cmd.version={{ .Env.RELEASE_VERSION }}"
      - -X "github.com/appgate/sdpctl/cmd.commit={{ .Commit }}"
      - -X "github.com/appgate/sdpctl/cmd.buildDate={{ .Date }}"
universal_binaries:
  - replace: false
    id: sdpctl_darwin
archives:
  - format_overrides:
      - goos: windows
        format: zip
checksum:
  name_template: "checksums.txt"
release:
  draft: true
  prerelease: auto
# signs:
#   - artifacts: checksum
nfpms:
  - homepage: https://www.appgate.com
    maintainer: Appgate Cybersecurity, Inc <appgatesdp.support@appgate.com>
    description: Command line tool for managing Appgate SDP collectives.
    formats:
      - deb
      - rpm
    contents:
      - src: ./build/bash_completion
        dst: /etc/bash_completion.d/sdpctl
      - src: ./build/man/*.gz
        dst: /usr/share/man/man3/
snapshot:
  name_template: "v{{ incpatch .Version }}"
changelog:
  sort: asc
  filters:
    exclude:
      - "^docs:"
      - "^test:"
