env:
  - RELEASE_VERSION={{ if index .Env "SDPCTL_VERSION" }}{{ .Env.SDPCTL_VERSION }}{{ else }}dev{{ end }}
before:
  hooks:
    - make deps
github_urls:
  download: https://github.com/appgate/sdpctl/releases
builds:
  - id: sdpctl
    main: ./main.go
    mod_timestamp: "{{ .CommitTimestamp }}"
    env:
      - CGO_ENABLED=0
    goos:
      - linux
      - windows
      - darwin
    goarch:
      - amd64
      - arm64
    no_unique_dist_dir: true
    binary: "{{ .ProjectName }}_{{ .Os }}_{{ .Arch }}/{{ if .IsSnapshot }}{{ .ProjectName }}_{{ .Os }}_{{ .Arch }}{{ else }}{{ .ProjectName }}{{ end }}"
    ldflags:
      - -s -w -X "github.com/appgate/sdpctl/cmd.version={{ .Env.RELEASE_VERSION }}"
      - -X "github.com/appgate/sdpctl/cmd.commit={{ .Commit }}"
      - -X "github.com/appgate/sdpctl/cmd.buildDate={{ .Date }}"
    ignore:
      - goos: darwin
        goarch: arm64
universal_binaries:
  - replace: false
    id: sdpctl
archives:
  - format_overrides:
      - goos: windows
        format: zip
checksum:
  name_template: "checksums.txt"
release:
  draft: true
  prerelease: auto
# signs:
#   - artifacts: checksum
nfpms:
  - homepage: https://www.appgate.com
    maintainer: Appgate Cybersecurity, Inc <appgatesdp.support@appgate.com>
    description: |-
      Command line tool for managing Appgate SDP collectives
    license: MIT
    formats:
      - deb
      - rpm
    contents:
      - src: ./build/bash_completion
        dst: /usr/share/bash-completion/completions/sdpctl
        file_info:
          mode: 0644
          group: root
      - src: ./build/man/*.gz
        dst: /usr/share/man/man3/
    deb:
      lintian_overrides:
        - statically-linked-binary
        - changelog-file-missing-in-native-package
    rpm:
      compression: lzma
snapshot:
  name_template: "{{ incpatch .Version }}"
changelog:
  sort: asc
  groups:
    - title: Features
      regexp: "^.*feat[(\\w)]*:+.*$"
      order: 0
    - title: "Bug Fixes"
      regexp: "^.*fix[(\\w)]*:+.*$"
      order: 1
    - title: Other
      order: 999
  filters:
    exclude:
      - "^docs:"
      - "^test:"
