# This is an example .goreleaser.yml file with some sensible defaults.
# Make sure to check the documentation at https://goreleaser.com
env:
 - RELEASE_VERSION={{ if index .Env "APPGATECTL_VERSION" }}{{ .Env.APPGATECTL_VERSION }}{{ else }}dev{{ end }}
builds:
  - main: ./main.go
    env:
      - CGO_ENABLED=0
    goos:
      - linux
      - windows
      - darwin
    goarch:
      - amd64
    ldflags:
    - -s -w -X "github.com/appgate/appgatectl/cmd.version={{ .Env.RELEASE_VERSION }}"
    - -X "github.com/appgate/appgatectl/cmd.commit={{ .Commit }}"
    - -X "github.com/appgate/appgatectl/cmd.buildDate={{ .Date }}"
archives:
  - replacements:
      386: i386
    format_overrides:
      - goos: windows
        format: zip
checksum:
  name_template: 'checksums.txt'
release:
  draft: true
  prerelease: auto
# signs:
#   - artifacts: checksum
nfpms:
  - homepage: https://www.appgate.com
    maintainer: Appgate Cybersecurity, Inc <appgatesdp.support@appgate.com>
    description: Command line tool for managing Appgate SDP collectives.
    formats:
      - deb
      - rpm
snapshot:
  name_template: "v{{ incpatch .Version }}"
changelog:
  sort: asc
  filters:
    exclude:
      - '^docs:'
      - '^test:'
