env:
  - RELEASE_VERSION={{ if index .Env "SDPCTL_VERSION" }}{{ .Env.SDPCTL_VERSION }}{{ else }}dev{{ end }}
before:
  hooks:
    - make deps
github_urls:
  download: https://github.com/appgate/sdpctl/releases
builds:
  - id: sdpctl
    main: ./main.go
    mod_timestamp: "{{ .CommitTimestamp }}"
    env:
      - CGO_ENABLED=0
    goos:
      - linux
      - windows
      - darwin
    goarch:
      - amd64
      - arm64
    binary: "{{ if .IsSnapshot }}{{ .ProjectName }}_{{ .Os }}_{{ .Arch }}{{ else }}{{ .ProjectName }}{{ end }}"
    ldflags:
      - -s -w -X "github.com/appgate/sdpctl/cmd.version={{ .Env.RELEASE_VERSION }}"
      - -X "github.com/appgate/sdpctl/cmd.commit={{ .Commit }}"
      - -X "github.com/appgate/sdpctl/cmd.buildDate={{ .Date }}"
    ignore:
      - goos: darwin
        goarch: arm64
universal_binaries:
  - replace: false
    id: sdpctl
archives:
  - format_overrides:
      - goos: windows
        format: zip
checksum:
  name_template: "checksums.txt"
release:
  draft: true
  prerelease: auto
# signs:
#   - artifacts: checksum
nfpms:
  - homepage: https://www.appgate.com
    maintainer: Appgate Cybersecurity Inc <appgatesdp.support@appgate.com>
    description: |-
      Official command line tool for managing
      Appgate SDP Collectives
    license: MIT
    vendor: Appgate Cybersecurity, Inc
    section: utils
    formats:
      - deb
      - rpm
    contents:
      - src: ./build/bash_completion
        dst: /usr/share/bash-completion/completions/sdpctl
        file_info:
          mode: 0644
          group: root
      - src: ./build/man/*.gz
        dst: /usr/share/man/man3/
        type: documentation
      - src: LICENSE
        dst: /usr/share/doc/sdpctl/copyright
        type: documentation
        file_info:
          group: root
          mode: 0644
    deb:
      lintian_overrides:
        - statically-linked-binary
        - changelog-file-missing-in-native-package
        - groff-message
    rpm:
      compression: gzip
snapshot:
  name_template: "{{ incpatch .Version }}"
changelog:
  use: github-native
