name: Go

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:

  test:
    name: Testing
    runs-on: ubuntu-latest
    steps:

    - name: Set up Go 1.x
      uses: actions/setup-go@v2
      with:
        go-version: ^1.16
      id: go

    - name: Check out code into the Go module directory
      uses: actions/checkout@v2

    - name: Get dependencies
      run: |
        go get -v -t -d ./...

    - name: Test formatting
      run: make fmtcheck

    - name: Unit tests
      run: make test

    - name: Test compiling
      run: make build

  lint:
    name: "Run static analysis"
    runs-on: "ubuntu-latest"
    steps:
    - uses: WillAbides/setup-go-faster@v1.5.0
      with:
        go-version: "1.16.x"
    - run: "GO111MODULE=on go get honnef.co/go/tools/cmd/staticcheck"
    - uses: actions/checkout@v1
      with:
        fetch-depth: 1
    - uses: actions/cache@v2
      with:
        path: ~/.cache/staticcheck
        key: staticcheck-${{ github.sha }}
        restore-keys: |
          staticcheck-
    - run: "go vet ./..."
    - run: "$(go env GOPATH)/bin/staticcheck -go 1.15 ./..."

  build:
    name: Build
    runs-on: ubuntu-latest
    needs: [test, lint]
    if: startsWith(github.ref, 'refs/heads/main')
    steps:

    - name: Set up Go 1.x
      uses: actions/setup-go@v2
      with:
        go-version: ^1.16
      id: go

    - name: Check out code into the Go module directory
      uses: actions/checkout@v2

    - name: 'Goreleaser build'
      uses: goreleaser/goreleaser-action@v2
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        APPGATECTL_VERSION: $($env:GITHUB_REF -replace "refs/tags/")
      with:
        args: "release"
