on:
  workflow_call:
    inputs: {}
    secrets: {}

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: Check out code into the Go module directory
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Fetch all tags
        run: git fetch --force --tags

      - name: Set up Go 1.x
        uses: actions/setup-go@v3
        with:
          go-version: ^1.18
        id: go

      - name: GoReleaser release dry run
        run: make release-dry-run

      - name: Setup release environment
        run: |-
          echo 'GITHUB_TOKEN=${{ secrets.GITHUB_TOKEN }}' >> .release-env
          echo 'SDPCTL_VERSION=${{ github.ref_name }}' >> .release-env
          echo 'SDPCTL_CONFIG_DIR=/go/src/github.com/user/repo' >> .release-env

      - name: GoReleaser release
        run: make release
