on:
  workflow_call:
    inputs: {}
    secrets: {}

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: Check out code into the Go module directory
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Fetch all tags
        run: git fetch --force --tags

      - name: Set up Go 1.x
        uses: actions/setup-go@v3
        with:
          go-version: ^1.18
        id: go

      - name: "Goreleaser build"
        uses: goreleaser/goreleaser-action@v3
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          SDPCTL_VERSION: ${{ github.ref_name }}
        with:
          distribution: goreleaser
          version: v1.9.2
          args: "release"
