name: Release Flow

on:
  push:
    branches:
      - main
    tags:
      - v*

jobs:
  test:
    uses: ./.github/workflows/test.yml@main
  lint:
    uses: ./.github/workflows/lint.yml@main
  release:
    if: ${{ github.ref_type == "tag" }}
    uses: ./.github/workflows/release.yml@main
    needs: [test, lint]
