name: Test Branch

on:
  push:
    branches-ignore:
      - main
  pull_request:
    branches:
      - main

jobs:
  test:
    uses: appgate/sdpctl/.github/workflows/test.yml@actions-rework
  lint:
    uses: appgate/sdpctl/.github/workflows/lint.yml@actions-rework
