name: Test Flow

on:
  push:
    branches:
      - "*"
  pull_request:
    branches:
      - main

jobs:
  test:
    uses: ./.github/workflows/test.yml@main
  lint:
    uses: ./.github/workflows/lint.yml@main
